// Generated by dsh-plugin-prepare. Do not edit.
const manifest = {"name":"whale-girl","skills":[],"entry":"./index.mjs"}
// Value mirror: Cordis const enum FiberState.ACTIVE; keep aligned with dsh-repository-plugin source.ts.
const FIBER_ACTIVE = 2
export const name = "whale-girl"
export const inject = ["loader"]
function unwrap(exports) {
  const value = exports?.default ?? exports
  return value?.__esModule ? (value.default ?? value) : value
}
async function mount(ctx, plugin, label, config) {
  const fiber = ctx.plugin(plugin, config)
  await fiber
  if (fiber.state !== FIBER_ACTIVE) {
    const missing = Object.keys(fiber.inject).filter(service => fiber.ctx.get(service) === undefined)
    throw new Error(`${label} did not activate (waiting for services: ${missing.join(', ') || 'unknown'})`)
  }
}
export async function apply(ctx) {
  const runtime = ctx.loader.builtins["dsh-repository-plugin"]
  if (runtime === undefined) throw new Error("missing Cordis builtin dsh-repository-plugin")
  await mount(ctx, runtime, 'repository Plugin runtime', { baseUrl: import.meta.url, manifest })
  const repositoryPlugin = unwrap(await import(manifest.entry))
  await mount(ctx, repositoryPlugin, 'repository Plugin entry')
}
